### ISSUE TITLE
Marking Menu stuck on

### ISSUE THREAD

**Issue by Redcroft** [DavideAlidosi/May9#1]
Hi, using the latest 1.1.1 on Maya 2017  linux, the marking menu is stuck on, and i am unable to do anything. Left click always shows the marking menu, meaning i cannot select or interact with the viewport. Holding down z, releasing z, pressing z does nothing to rectify this.

**Comment by DavideAlidosi** [comment]
Hi, can you please try the currrent 1.1.2 from github and tell me if it fix?

**Comment by Redcroft** [comment]
Thank you, 1.1.2 fixed the issue
