### ISSUE TITLE
UV Toolkit

### ISSUE THREAD

**Issue by ArcticLatent** [DavideAlidosi/May9#3]
Hello Davide. I really enjoy using May9. It completely changed the way i use Maya. First of all thank you for all your great efforts!

I just want to ask a simple question. What is that UV Toolkit thats in the changelog? I can't find anything related to it. 

Thanks!

**Comment by DavideAlidosi** [comment]
Hello too, I'm glad you enjoy by using May9 :)!
UV Toolkit is a feature of Maya 2017 Update 3 (actually in beta and soon released), you can just ignore any reference on that or download and install the last stable version of May9 Pro from here: https://www.highend3d.com/maya/script/may9-pro-a-new-maya-user-experience-for-maya

Have a great day sir,
Davide
